"""listening form completion

Revision ID: 0afa371f1412
Revises: 6c868a7e30b2
Create Date: 2026-08-04 18:15:48.570019

Reconciliation (brief §4.5): the pre-existing ``attempts`` table (added by
``dd82d01c9cec_core_schema``) was empty and unreferenced by any application
code — nothing in ``app/`` queried or wrote to it. Rather than adding a
parallel listening-attempts table, this migration reshapes ``attempts`` in
place into the general, material-type-agnostic ``Attempt`` from the brief:
it gains ``status``/``total_questions``/``started_at``/``submitted_at`` for
listening, while ``score``/``time_spent_ms``/``completed_at`` (the
dictation-era columns) become nullable so dictation and listening attempts
share one row shape. ``QuestionAttempt`` is added as the listening analog of
the existing dictation ``segment_attempts`` table — the per-question
event-sourcing atom, not a duplicate of it.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in autogen output
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0afa371f1412'
down_revision: Union[str, Sequence[str], None] = '6c868a7e30b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_start_ms', sa.Integer(), nullable=True),
    sa.Column('audio_end_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name='fk_parts_material_id_materials'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'order_index', name='uq_parts_material_order')
    )
    op.create_index(op.f('ix_parts_material_id'), 'parts', ['material_id'], unique=False)
    op.create_table('question_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('part_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('word_limit', sa.Integer(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name='fk_question_groups_part_id_parts'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'order_index', name='uq_question_groups_part_order')
    )
    op.create_index(op.f('ix_question_groups_part_id'), 'question_groups', ['part_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('correct_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('replay_start_ms', sa.Integer(), nullable=True),
    sa.Column('replay_end_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['question_groups.id'], name='fk_questions_group_id_question_groups'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'number', name='uq_questions_group_number')
    )
    op.create_index(op.f('ix_questions_group_id'), 'questions', ['group_id'], unique=False)
    op.create_table('question_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('given_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], name='fk_question_attempts_attempt_id_attempts'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='fk_question_attempts_question_id_questions'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_attempts_attempt_id'), 'question_attempts', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_question_attempts_question_id'), 'question_attempts', ['question_id'], unique=False)
    op.add_column(
        'attempts',
        sa.Column(
            'status',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='in_progress',
        ),
    )
    op.add_column('attempts', sa.Column('total_questions', sa.Integer(), nullable=True))
    op.add_column(
        'attempts',
        sa.Column(
            'started_at',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text('now()'),
        ),
    )
    op.add_column('attempts', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('attempts', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('attempts', 'time_spent_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attempts', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempts', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('attempts', 'time_spent_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attempts', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('attempts', 'submitted_at')
    op.drop_column('attempts', 'started_at')
    op.drop_column('attempts', 'total_questions')
    op.drop_column('attempts', 'status')
    op.drop_constraint(
        'fk_question_attempts_question_id_questions', 'question_attempts', type_='foreignkey'
    )
    op.drop_constraint(
        'fk_question_attempts_attempt_id_attempts', 'question_attempts', type_='foreignkey'
    )
    op.drop_index(op.f('ix_question_attempts_question_id'), table_name='question_attempts')
    op.drop_index(op.f('ix_question_attempts_attempt_id'), table_name='question_attempts')
    op.drop_table('question_attempts')
    op.drop_constraint(
        'fk_questions_group_id_question_groups', 'questions', type_='foreignkey'
    )
    op.drop_index(op.f('ix_questions_group_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_constraint(
        'fk_question_groups_part_id_parts', 'question_groups', type_='foreignkey'
    )
    op.drop_index(op.f('ix_question_groups_part_id'), table_name='question_groups')
    op.drop_table('question_groups')
    op.drop_constraint(
        'fk_parts_material_id_materials', 'parts', type_='foreignkey'
    )
    op.drop_index(op.f('ix_parts_material_id'), table_name='parts')
    op.drop_table('parts')
    # ### end Alembic commands ###
