"""audio ingestion

Revision ID: 6c868a7e30b2
Revises: 9fd7ad2722f1
Create Date: 2026-08-02 18:55:34.373307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in autogen output


# revision identifiers, used by Alembic.
revision: str = '6c868a7e30b2'
down_revision: Union[str, Sequence[str], None] = '9fd7ad2722f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_blob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transcript_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transcript_attempts', sa.Integer(), nullable=False),
    sa.Column('transcript_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_blob_sha256'), 'audio_blob', ['sha256'], unique=True)
    op.create_table('audio_asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('blob_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blob_id'], ['audio_blob.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'blob_id', name='uq_audio_asset_owner_blob')
    )
    op.create_index(op.f('ix_audio_asset_blob_id'), 'audio_asset', ['blob_id'], unique=False)
    op.create_index(op.f('ix_audio_asset_owner_id'), 'audio_asset', ['owner_id'], unique=False)
    op.create_table('audio_segment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('blob_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('words', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blob_id'], ['audio_blob.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blob_id', 'order_index', name='uq_audio_segment_blob_order')
    )
    op.create_index(op.f('ix_audio_segment_blob_id'), 'audio_segment', ['blob_id'], unique=False)
    op.add_column('materials', sa.Column('audio_asset_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_materials_audio_asset_id'), 'materials', ['audio_asset_id'], unique=False)
    op.create_foreign_key(
        'fk_materials_audio_asset_id_audio_asset',
        'materials', 'audio_asset', ['audio_asset_id'], ['id'],
    )
    op.drop_column('materials', 'audio_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('audio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(
        'fk_materials_audio_asset_id_audio_asset', 'materials', type_='foreignkey'
    )
    op.drop_index(op.f('ix_materials_audio_asset_id'), table_name='materials')
    op.drop_column('materials', 'audio_asset_id')
    op.drop_index(op.f('ix_audio_segment_blob_id'), table_name='audio_segment')
    op.drop_table('audio_segment')
    op.drop_index(op.f('ix_audio_asset_owner_id'), table_name='audio_asset')
    op.drop_index(op.f('ix_audio_asset_blob_id'), table_name='audio_asset')
    op.drop_table('audio_asset')
    op.drop_index(op.f('ix_audio_blob_sha256'), table_name='audio_blob')
    op.drop_table('audio_blob')
    # ### end Alembic commands ###
