"""audio asset transcript overrides

Revision ID: 8e971e17d8f8
Revises: b59b2f964079
Create Date: 2026-08-11 13:22:00.618104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in autogen output
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e971e17d8f8'
down_revision: Union[str, Sequence[str], None] = 'b59b2f964079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_asset', sa.Column('transcript_overrides', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_asset', 'transcript_overrides')
    # ### end Alembic commands ###
