"""material updated_at

Revision ID: b59b2f964079
Revises: 0afa371f1412
Create Date: 2026-08-07 07:20:20.138409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in autogen output


# revision identifiers, used by Alembic.
revision: str = 'b59b2f964079'
down_revision: Union[str, Sequence[str], None] = '0afa371f1412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'updated_at')
    # ### end Alembic commands ###
