"""vocabulary: a passage's words, glossed in that passage's own sense

Revision ID: b9026b88a3c3
Revises: c7d41f28b9a3
Create Date: 2026-09-20 17:40:00.000000

Three tables and one column, and the shape of them is the argument.

``material_vocabulary`` is per material, not a dictionary. A global words
table with one meaning each throws away the only expensive thing here: what
the word means IN THIS PASSAGE. ``spring`` is a season in one and a coil in
the next, and a single stored sense is wrong for most of the passages that
use it -- which is exactly why a plain dictionary API is no use to a band 5
reader. The duplication is a few kilobytes; the alternative costs the
feature.

``saved_words`` and ``saved_word_contexts`` deduplicate in the one place
where deduplicating means something. What a learner is STUDYING is one word,
however many passages they met it in; the senses and example sentences
survive as contexts hanging off it, which makes a better flashcard than
either the word alone or a list of unrelated rows.

The gloss is copied into the context rather than read back through
``vocabulary_id``. A material can be edited and re-glossed, and a saved word
silently changing meaning underneath somebody is worse than a copy that has
aged. The id is kept as provenance and as what stops one material being
saved twice.

``attempts.looked_up`` is a JSONB list of lemmas, on the same reading as
``parts.passage``: written once at submit, read by exactly one screen, never
joined and never aggregated. Null means the attempt predates the
measurement; an empty list means they looked nothing up, which on a reading
paper is a real and different fact.

Additive throughout. The autogenerated draft of this also proposed dropping
the four hand-written trigram and catalogue indexes -- ``ix_materials_
catalogue``, the three ``_trgm`` ones -- which Alembic cannot see in the
model metadata and therefore believes are strays. They are not, and this
revision leaves them alone.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b9026b88a3c3'
down_revision: Union[str, Sequence[str], None] = 'c7d41f28b9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('saved_words',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lemma', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lemma', name='uq_saved_user_lemma')
    )
    op.create_index(op.f('ix_saved_words_lemma'), 'saved_words', ['lemma'], unique=False)
    op.create_index(op.f('ix_saved_words_user_id'), 'saved_words', ['user_id'], unique=False)
    op.create_table('material_vocabulary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('part_id', sa.Uuid(), nullable=False),
    sa.Column('lemma', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('surface', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('pos', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('meaning_en', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('meaning_uz', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('example', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=False),
    sa.Column('paragraph_index', sa.Integer(), nullable=False),
    sa.Column('offset_start', sa.Integer(), nullable=False),
    sa.Column('offset_end', sa.Integer(), nullable=False),
    sa.Column('cefr_level', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('frequency_band', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('is_phrase', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'lemma', name='uq_vocab_material_lemma')
    )
    op.create_index(op.f('ix_material_vocabulary_cefr_level'), 'material_vocabulary', ['cefr_level'], unique=False)
    op.create_index(op.f('ix_material_vocabulary_material_id'), 'material_vocabulary', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_vocabulary_part_id'), 'material_vocabulary', ['part_id'], unique=False)
    op.create_table('saved_word_contexts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('saved_word_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('vocabulary_id', sa.Uuid(), nullable=True),
    sa.Column('surface', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('pos', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('meaning_en', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('meaning_uz', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('example', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=False),
    sa.Column('cefr_level', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('is_phrase', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['saved_word_id'], ['saved_words.id'], ),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['material_vocabulary.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saved_word_id', 'material_id', name='uq_saved_context_material')
    )
    op.create_index(op.f('ix_saved_word_contexts_material_id'), 'saved_word_contexts', ['material_id'], unique=False)
    op.create_index(op.f('ix_saved_word_contexts_saved_word_id'), 'saved_word_contexts', ['saved_word_id'], unique=False)
    op.add_column(
        "attempts",
        sa.Column("looked_up", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("attempts", "looked_up")
    op.drop_table("saved_word_contexts")
    op.drop_table("material_vocabulary")
    op.drop_table("saved_words")
